### ISSUE TITLE
Attempting to run on older 3rd gen Kindle (keyboard)

### ISSUE THREAD

**Issue by jamorris** [scolby33/weather_kindle#1]
I’m using a Kindle 3rd gen (Keyboard) and can’t find a version of `rsvg-convert` that will run. 'Weather Kindle' will create an updated weather/img/weather_out.svg but without a compatible `rsvg-convert` the program halts. Do you have any advice on how to find a compatible `rsvg-convert` or another way to create the needed .png file?

**Comment by scolby33** [comment]
I definitely struggled with this on my Kindle 4. What output do you get exactly when you try to run the `rsvg-convert` binaries you've found?

I originally got my copy of `rsvg-convert` from the [Debian repositories](https://packages.debian.org/buster/librsvg2-bin) by manually resolving and downloading dependencies and setting `LD_LIBRARY_PATH`. Eventually I modified my binaries with `patchelf`.

**Comment by jamorris** [comment]
Thanks for getting back to me. I get this error:
```
./rsvg-convert: /lib/libc.so.6: version `GLIBC_2.7' not found (required by ../lib/librsvg-2.so.2)
./rsvg-convert: /lib/libc.so.6: version `GLIBC_2.7' not found (required by ../lib/libgsf-1.so.114)
./rsvg-convert: /lib/libc.so.6: version `GLIBC_2.7' not found (required by ../lib/libxml2.so.2)
```
I think I have GLIBC 2.5 (“GNU C Library stable release version 2.5”)
I was able to run a chroot via [Debian_Installation_on_Kindle_Touch](https://wiki.mobileread.com/wiki/Debian_Installation_on_Kindle_Touch) and install `rsvg-convert` via `apt-get`. I was surprised that it was actually able to convert an .svg to .png on the Kindle in the chroot environment. I tried copying the executable from the chroot environment and linking the libraries but it didn't work. It failed with ‘Illegal instruction’.
I noticed that the built-in web browser can open .svg files. Do you know if there is a way to trigger the browser to open a file from a command?

**Comment by scolby33** [comment]
What version of libc does the Kindle 3 have?

https://www.linuxquestions.org/questions/linux-software-2/how-to-check-glibc-version-263103/

**Comment by jamorris** [comment]
2.5
```
[root@kindle bin]# /lib/libc.so.6
GNU C Library stable release version 2.5, by Roland McGrath et al.
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 4.1.2.
Compiled on a Linux 2.6.15 system on 2008-06-10.
Available extensions:
	crypt add-on version 2.1 by Michael Glad and others
	GNU Libidn by Simon Josefsson
	GNU libio by Per Bothner
	NIS(YP)/NIS+ NSS modules 0.19 by Thorsten Kukuk
	Native POSIX Threads Library by Ulrich Drepper et al
	Support for some architectures added on, not maintained in glibc core.
	BIND-8.2.3-T5B
Thread-local storage support included.
For bug reporting instructions, please see:
<http://www.gnu.org/software/libc/bugs.html>.
```

**Comment by scolby33** [comment]
Interesting. I'll see what I can figure out with this this weekend--I have a Kindle 4 and a Paperwhite to test with.

**Comment by jamorris** [comment]
Thanks. I appreciate the help. I tested again with chroot running on the Kindle and it was able to convert the .svg to a .png then run `pngcrush` to make the final .png. Now I just need to find a reliable way to use the chroot environment to do the file conversion. It’s not pretty but at least it won’t need a server.

**Comment by jamorris** [comment]
I modified the script from
```
/mnt/us/weather/bin/rsvg-convert --background-color=white -o img/weather_out.png img/weather_out.svg
```
to
```
chroot /mnt/debian /bin/bash -c "rsvg-convert --background-color=white -o /mnt/us/weather/img/weather_out.png /mnt/us/weather/img/weather_out.svg"
```
and now it works. Using chroot isn't as elegant but it means I don't need a server to convert the files.

**Comment by scolby33** [comment]
I am unable to duplicate your issue on the Kindles that I have, unfortunately. I agree with you that the chroot isn't the ideal solution, but I'm glad my other work proved useful :)

Closing for now, but feel free to reopen if there is more to add.

**Comment by jamorris** [comment]
I've been running `weather_kindle` with chroot for a week and it's working well. It's a great way to put the old Kindle to use. Thanks for your help and for making weather_kindle available.
