### ISSUE TITLE
PW1

### ISSUE THREAD

**Issue by radezivanovic** [scolby33/weather_kindle#11]
Hey,
could you create a version for paperwhite 1?

Thanks

**Comment by scolby33** [comment]
Sorry for the delay! Please check out the new release. https://github.com/scolby33/weather_kindle/releases/tag/v1.0.3

Feel free to re-open if it doesn't work!

**Comment by radezivanovic** [comment]
thanks, appreciate your effort. I've just tried installing it and got an error message in MR Installer: "Package script failed (2), moving on... :(". A GUI restart is triggered after that and there's no sign of the weather app. As a prerequisite I've installed python 3.

**Comment by Elendiir1970** [comment]
Hi Scolby33,

thanks for your work. I would love to install weather kindle on my PW1. But unfortunately I also do get the same error message as radezivanovic during installation. Any idea how to solve the installation error. Is there anything that I can do to either solved the issue or help you solving the issue?
