### ISSUE TITLE
World Meterological Organization method does not work

### ISSUE THREAD

**Issue by vladime** [scolby33/weather_kindle#2]
I have used city_id 58 for WMO in the config file but unfortunately kindle returns "error.png" picture. I have kindle 4. 
All other methods are working fine. Have you tested WMO method on your K4?

**Comment by scolby33** [comment]
I have validation in the code that requires WMO city id's to be 3 or 4 characters long. I must have missed that they can possibly be only two digits. Let me check on this and push a fix.

**Comment by scolby33** [comment]
Yep! I actually made a couple mistakes here with the WMO configuration. I've opened a PR at #3 with a fix that works for me, but it'd be great if you could test this build as well. I've made installer and uninstaller updates for the branch and attached them here. Can you try this out on your Kindle and let me know how it works? It's safe to install the update over your existing installation.

[Update_weather_k4_wmo_parsing_improvements.zip](https://github.com/scolby33/weather_kindle/files/6138371/Update_weather_k4_wmo_parsing_improvements.zip)

**Comment by vladime** [comment]
Thank for the prompt response and a quick fix! I had to uninstall existing version to have a clean test for "Update_weather_k4_wmo_parsing_improvements.zip" version. Now WMO option works but only with "Imperial" units. As soon as I enable "Metric" option in config file I get error page on the screen.

**Comment by scolby33** [comment]
🤦 I made a second silly mistake in fixing the first one. Here's another build to try.
[Update_weather_k4_wmo_parsing_improvements.zip](https://github.com/scolby33/weather_kindle/files/6141884/Update_weather_k4_wmo_parsing_improvements.zip)

**Comment by vladime** [comment]
METRIC="1"
CITY_ID="58"

This my ***weather_config.sh*** file. The output is still imperial (F) not metric (C).

**Comment by scolby33** [comment]
You're right, turns out WMO metric output was never working. Yet another test build :)

[Update_weather_k4_wmo_parsing_improvements.zip](https://github.com/scolby33/weather_kindle/files/6142292/Update_weather_k4_wmo_parsing_improvements.zip)

**Comment by vladime** [comment]
After the test:
- Still "Imperial" units despite "Metric" option enabled
- First day forecast is tomorrow (like in AccuWeather before fix)
Should I open another Issue or let's keep it here?

**Comment by scolby33** [comment]
Oh, I guess I jumped too quickly. Let's open a new one and I'll be able to look at it later tonight :)

**Comment by scolby33** [comment]
Oh, I screwed up by not fully pushing a branch. #6 should fix it, give me a few minutes to cut a new release.
