### ISSUE TITLE
WMO only imperial units, shifted date display

### ISSUE THREAD

**Issue by vladime** [scolby33/weather_kindle#7]
1. WMO method does not support metric option
2. First forecast displayed day is tomorrow

**Comment by scolby33** [comment]
1. Please try the new v1.0.2 release
2. I can't do anything about this for the WMO, their published forecasts start with tomorrow.

**Comment by vladime** [comment]
1. Confirmed. The issue is fixed. 
2. Now I understand. WMO provides forecast ones a day at 10:00 a.m. for a next few days and does not provide data for the current one (for whatever reason).

Mr. Colby I really appreciate your help. Thank you.

**Comment by scolby33** [comment]
No problem! Thanks for using weather_kindle and helping me find my bugs!
